<Project>
  <ItemGroup>
    <PackageVersion Include="DuckDB.NET.Data.Full" Version="1.5.5" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageVersion Include="Npgsql" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Data.SqlClient" Version="7.0.3" />
    <PackageVersion Include="System.CommandLine" Version="2.0.12" />
    <PackageVersion Include="DocumentFormat.OpenXml" Version="3.1.1" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
    <PackageVersion Include="Shouldly" Version="4.3.0" />
  </ItemGroup>
</Project>
