<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>GalaxyData.Web</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.OpenApi" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GalaxyData.Query\GalaxyData.Query.csproj" />
    <ProjectReference Include="..\GalaxyData.Query.DuckDb\GalaxyData.Query.DuckDb.csproj" />
    <ProjectReference Include="..\GalaxyData.Query.Excel\GalaxyData.Query.Excel.csproj" />
    <ProjectReference Include="..\GalaxyData.Query.PostgreSql\GalaxyData.Query.PostgreSql.csproj" />
    <ProjectReference Include="..\GalaxyData.Query.Sqlite\GalaxyData.Query.Sqlite.csproj" />
    <ProjectReference Include="..\GalaxyData.Query.SqlServer\GalaxyData.Query.SqlServer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GalaxyData.Web.Tests" />
  </ItemGroup>

</Project>
