<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>GalaxyData.Query.Excel</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GalaxyData.Query.ContainerTests" />
    <InternalsVisibleTo Include="GalaxyData.Query.IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GalaxyData.Query.DuckDb\GalaxyData.Query.DuckDb.csproj" />
  </ItemGroup>

</Project>
