using System;
using System.Collections.Frozen;

namespace GalaxyData.Query.Sql;

/// <summary>
/// Words that are quoted when used as names. One list for every dialect: the reserved words of standard SQL and
/// of the four supported databases, plus a few that are only awkward. Quoting too much is harmless.
/// </summary>
internal static class SqlKeywords
{
   private static readonly FrozenSet<string> Words = new[]
   {
      "ABORT", "ABSOLUTE", "ACTION", "ADD", "ALL", "ALLOCATE", "ALTER", "ALWAYS", "ANALYSE", "ANALYZE", "AND", "ANTI", "ANY",
      "ARE", "ARRAY", "AS", "ASC", "ASOF", "ASYMMETRIC", "AT", "ATTACH", "AUTHORIZATION", "AUTOINCREMENT", "BACKUP",
      "BEFORE", "BEGIN", "BETWEEN", "BIGINT", "BINARY", "BIT", "BLOB", "BOOLEAN", "BOTH", "BREAK", "BROWSE", "BULK", "BY",
      "CALL", "CASCADE", "CASE", "CAST", "CHAR", "CHARACTER", "CHECK", "CHECKPOINT", "CLOSE", "CLUSTERED", "COALESCE",
      "COLLATE", "COLLATION", "COLUMN", "COLUMNS", "COMMIT", "COMPUTE", "CONCURRENTLY", "CONFLICT", "CONNECT", "CONSTRAINT",
      "CONTAINS", "CONTAINSTABLE", "CONTINUE", "CONVERT", "CREATE", "CROSS", "CUBE", "CURRENT", "CURRENT_CATALOG",
      "CURRENT_DATE", "CURRENT_ROLE", "CURRENT_SCHEMA", "CURRENT_TIME", "CURRENT_TIMESTAMP", "CURRENT_USER", "CURSOR",
      "DATABASE", "DATE", "DAY", "DBCC", "DEALLOCATE", "DEC", "DECIMAL", "DECLARE", "DEFAULT", "DEFERRABLE", "DEFERRED",
      "DELETE", "DENY", "DESC", "DESCRIBE", "DETACH", "DISK", "DISTINCT", "DISTRIBUTED", "DO", "DOUBLE", "DROP", "DUMP",
      "EACH", "ELSE", "END", "ERRLVL", "ESCAPE", "EXCEPT", "EXCLUDE", "EXCLUSIVE", "EXEC", "EXECUTE", "EXISTS", "EXIT",
      "EXPLAIN", "EXTERNAL", "EXTRACT", "FAIL", "FALSE", "FETCH", "FILE", "FILLFACTOR", "FILTER", "FIRST", "FLOAT", "FOR",
      "FOREIGN", "FREETEXT", "FREETEXTTABLE", "FREEZE", "FROM", "FULL", "FUNCTION", "GENERATED", "GLOB", "GOTO", "GRANT",
      "GROUP", "GROUPS", "HAVING", "HOLDLOCK", "HOUR", "IDENTITY", "IDENTITYCOL", "IDENTITY_INSERT", "IF", "IGNORE", "ILIKE",
      "IMMEDIATE", "IN", "INDEX", "INDEXED", "INITIALLY", "INNER", "INSERT", "INSTEAD", "INT", "INTEGER", "INTERSECT",
      "INTERVAL", "INTO", "IS", "ISNULL", "JOIN", "KEY", "KILL", "LAST", "LATERAL", "LEADING", "LEFT", "LIKE", "LIMIT",
      "LINENO", "LOAD", "LOCALTIME", "LOCALTIMESTAMP", "MAP", "MATCH", "MATERIALIZED", "MERGE", "MINUTE", "MONTH",
      "NATIONAL", "NATURAL", "NCHAR", "NO", "NOCHECK", "NONCLUSTERED", "NOT", "NOTHING", "NOTNULL", "NULL", "NULLIF",
      "NULLS", "NUMERIC", "OF", "OFF", "OFFSET", "OFFSETS", "ON", "ONLY", "OPEN", "OPENDATASOURCE", "OPENQUERY",
      "OPENROWSET", "OPENXML", "OPTION", "OR", "ORDER", "OTHERS", "OUTER", "OVER", "OVERLAPS", "PARTITION", "PERCENT",
      "PIVOT", "PLACING", "PLAN", "POSITIONAL", "PRAGMA", "PRECISION", "PRIMARY", "PRINT", "PROC", "PROCEDURE", "PUBLIC",
      "QUALIFY", "QUERY", "RAISE", "RAISERROR", "RANGE", "READ", "READTEXT", "REAL", "RECONFIGURE", "RECURSIVE",
      "REFERENCES", "REGEXP", "REINDEX", "RELEASE", "RENAME", "REPLACE", "REPLICATION", "RESTORE", "RESTRICT",
      "RETURN", "RETURNING", "REVERT", "REVOKE", "RIGHT", "ROLLBACK", "ROW", "ROWCOUNT", "ROWGUIDCOL", "ROWS", "RULE",
      "SAVE", "SAVEPOINT", "SCHEMA", "SECOND", "SECURITYAUDIT", "SELECT", "SEMANTICKEYPHRASETABLE",
      "SEMANTICSIMILARITYDETAILSTABLE", "SEMANTICSIMILARITYTABLE", "SEMI", "SESSION_USER", "SET", "SETOF", "SETUSER",
      "SHUTDOWN", "SIMILAR", "SMALLINT", "SOME", "STATISTICS", "STRUCT", "SUMMARIZE", "SYMMETRIC", "SYSTEM_USER",
      "TABLE", "TABLESAMPLE", "TEMP", "TEMPORARY", "TEXTSIZE", "THEN", "TIES", "TIME", "TIMESTAMP", "TO", "TOP",
      "TRAILING", "TRAN", "TRANSACTION", "TRIGGER", "TRUE", "TRUNCATE", "TRY_CONVERT", "TSEQUAL", "UNBOUNDED", "UNION",
      "UNIQUE", "UNPIVOT", "UPDATE", "UPDATETEXT", "USE", "USER", "USING", "VACUUM", "VALUE", "VALUES", "VARCHAR",
      "VARIADIC", "VARYING", "VERBOSE", "VIEW", "VIRTUAL", "WAITFOR", "WHEN", "WHERE", "WHILE", "WINDOW", "WITH",
      "WITHIN", "WITHOUT", "WRITETEXT", "YEAR",
   }.ToFrozenSet(StringComparer.OrdinalIgnoreCase);

   public static bool IsKeyword(string name) => Words.Contains(name);
}
