<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>GalaxyData.Query</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GalaxyData.Common\GalaxyData.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GalaxyData.Query.Tests" />
  </ItemGroup>

</Project>
