<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>gdq</AssemblyName>
    <RootNamespace>GalaxyData.Query.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GalaxyData.Query\GalaxyData.Query.csproj" />
    <ProjectReference Include="..\GalaxyData.Query.DuckDb\GalaxyData.Query.DuckDb.csproj" />
    <ProjectReference Include="..\GalaxyData.Query.Excel\GalaxyData.Query.Excel.csproj" />
    <ProjectReference Include="..\GalaxyData.Query.PostgreSql\GalaxyData.Query.PostgreSql.csproj" />
    <ProjectReference Include="..\GalaxyData.Query.Sqlite\GalaxyData.Query.Sqlite.csproj" />
    <ProjectReference Include="..\GalaxyData.Query.SqlServer\GalaxyData.Query.SqlServer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GalaxyData.Query.ContainerTests" />
    <InternalsVisibleTo Include="GalaxyData.Query.IntegrationTests" />
  </ItemGroup>

</Project>
