<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>GalaxyData.Connectors.BuiltIn</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GalaxyData.Connectors\GalaxyData.Connectors.csproj" />
    <ProjectReference Include="..\GalaxyData.Query.ClickHouse\GalaxyData.Query.ClickHouse.csproj" />
    <ProjectReference Include="..\GalaxyData.Query.DuckDb\GalaxyData.Query.DuckDb.csproj" />
    <ProjectReference Include="..\GalaxyData.Query.Excel\GalaxyData.Query.Excel.csproj" />
    <ProjectReference Include="..\GalaxyData.Query.PostgreSql\GalaxyData.Query.PostgreSql.csproj" />
    <ProjectReference Include="..\GalaxyData.Query.Sqlite\GalaxyData.Query.Sqlite.csproj" />
    <ProjectReference Include="..\GalaxyData.Query.SqlServer\GalaxyData.Query.SqlServer.csproj" />
  </ItemGroup>

</Project>
