-- The shop fixture (PostgreSQL). Kept in step with shop.sqlite.sql and shop.duckdb.sql.
CREATE TABLE customers (
   id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name text NOT NULL,
   city varchar(40),
   credit_limit numeric(10,2),
   created_at timestamp DEFAULT now()
);
CREATE UNIQUE INDEX ux_customers_name ON customers(name);
COMMENT ON TABLE customers IS 'People and companies who order';
COMMENT ON COLUMN customers.credit_limit IS 'In rand';

CREATE TABLE addresses (
   id integer PRIMARY KEY,
   customer_id integer NOT NULL REFERENCES customers(id),
   line1 text NOT NULL,
   city text
);

CREATE TABLE orders (
   id bigint PRIMARY KEY,
   customer_id integer NOT NULL REFERENCES customers(id),
   ship_address_id integer REFERENCES addresses(id),
   bill_address_id integer REFERENCES addresses(id),
   status varchar(20) NOT NULL DEFAULT 'open',
   total numeric(10,2) NOT NULL,
   order_date date NOT NULL,
   placed_at timestamptz,
   tags text[]
);
CREATE INDEX ix_orders_status ON orders(status);
CREATE INDEX ix_orders_open ON orders(order_date) WHERE status = 'open';

CREATE TABLE order_lines (
   order_id bigint NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
   line_no integer NOT NULL,
   product_code varchar(20) NOT NULL,
   qty integer NOT NULL,
   price numeric(10,2) NOT NULL,
   amount numeric(12,2) GENERATED ALWAYS AS (qty * price) STORED,
   PRIMARY KEY (order_id, line_no)
);

CREATE TABLE employees (
   id integer PRIMARY KEY,
   name text NOT NULL,
   manager_id integer
);

CREATE TABLE audit_log (
   at timestamp,
   message text
);

CREATE SCHEMA crm;
CREATE TABLE crm.contacts (
   id uuid PRIMARY KEY,
   customer_ref integer,
   email text NOT NULL UNIQUE,
   "Display Name" text
);

CREATE VIEW open_orders AS SELECT id, customer_id, total FROM orders WHERE status = 'open';

CREATE FUNCTION log_order_update() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
   INSERT INTO audit_log(at, message) VALUES (now(), 'order ' || NEW.id || ' updated');
   RETURN NEW;
END $$;
CREATE TRIGGER trg_orders_updated AFTER UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION log_order_update();

INSERT INTO customers (id, name, city, credit_limit) VALUES
   (1, 'Acme Ltd', 'Cape Town', 5000.00),
   (2, 'Beta Corp', 'Johannesburg', 1000.00),
   (3, 'Gamma Inc', NULL, NULL);
INSERT INTO addresses (id, customer_id, line1, city) VALUES
   (1, 1, '1 Main Rd', 'Cape Town'),
   (2, 2, '9 High St', 'Johannesburg');
INSERT INTO orders (id, customer_id, ship_address_id, bill_address_id, status, total, order_date, placed_at) VALUES
   (1001, 1, 1, 1, 'open', 250.00, '2026-01-05', '2026-01-05 10:30:00+02:00'),
   (1002, 1, 1, NULL, 'shipped', 99.50, '2026-01-09', '2026-01-09 23:15:00-05:00'),
   (1003, 2, 2, 2, 'open', 12.25, '2026-02-01', '2026-01-05 11:00:00+05:00'),
   (1004, 3, NULL, NULL, 'cancelled', 0.00, '2026-02-14', NULL);
INSERT INTO order_lines (order_id, line_no, product_code, qty, price) VALUES
   (1001, 1, 'P-100', 2, 100.00),
   (1001, 2, 'P-200', 1, 50.00),
   (1002, 1, 'P-100', 1, 99.50),
   (1003, 1, 'P-300', 5, 2.45);
INSERT INTO employees (id, name, manager_id) VALUES (1, 'Ann', NULL), (2, 'Ben', 1), (3, 'Cal', 1);
-- The identity goes on from the customers given their ids.
SELECT setval(pg_get_serial_sequence('customers', 'id'), 3);
INSERT INTO crm.contacts VALUES ('2f1c0000-0000-4000-8000-000000000001', 1, 'ann@acme.test', 'Ann at Acme');
-- A foreign key added NOT VALID isn't checked against the rows already there.
ALTER TABLE employees ADD CONSTRAINT employees_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES employees(id) NOT VALID;
ANALYZE;
