<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>GalaxyData.Query.PostgreSql</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GalaxyData.Query\GalaxyData.Query.csproj" />
  </ItemGroup>

</Project>
