<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>GalaxyData.Query.ClickHouse</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClickHouse.Driver" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GalaxyData.Connectors\GalaxyData.Connectors.csproj" />
  </ItemGroup>

</Project>
