<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>GalaxyData.Query.DuckDb</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DuckDB.NET.Data.Full" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GalaxyData.Query.Excel" />
    <InternalsVisibleTo Include="GalaxyData.Query.ContainerTests" />
    <InternalsVisibleTo Include="GalaxyData.Query.IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GalaxyData.Query\GalaxyData.Query.csproj" />
  </ItemGroup>

</Project>
